[package]
name = "pasteplz-backend"
version = "0.1.0"
edition = "2021"

[dependencies]
toml = "0.5"
serde = { version = "1.0", features = ["derive"] }

chrono = { version = "0.4", features = ["serde"] }

tokio-postgres = "0.7.6"
deadpool-postgres = "0.10.2"

actix-web = "4"
